name: "Run pre-commit"
description: "Install Python, install pre-commit, and run it on all files"

inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.14"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - shell: bash
      run: pip install pre-commit

    - shell: bash
      run: pre-commit run --all-files
